# ego pose in world frame
ego_pose1_in_world_frame: 
  yaw: 0.0 # unit: deg
  pitch: 0.0
  roll: 0.0
  x: 0.0 # unit: m
  y: 0.0
  z: 0.0
ego_pose2_in_world_frame:
  yaw: 0.0
  pitch: 0.0
  roll: 0.0
  x: 0.0
  y: 0.0
  z: 0.0

# target pose in ego frame (rear wheel center) 
target_pose1_in_ego1_frame: 
  yaw: 0.0
  pitch: 0.0
  roll: 0.0
  x: 10.0
  y: 5.0
  z: 0.0
target_pose2_in_ego2_frame: 
  yaw: 0.0
  pitch: 0.0
  roll: 0.0
  x: 10.0
  y: 5.0
  z: 0.0

# target size
target_size:
  length: 4.0 #unit: m
  width: 2.0
  height: 2.0

# other target info
cell_size_on_target: 0.2 # unit: m

# lidar config
horizontal_angle_resolution: 0.2 # unit: deg
vertical_angle_resolution: 0.33 # unit : deg
laser_number: 40
horizontal_laser_index: 29
lidar_pose_in_ego_frame:
  yaw: 0.0 # unit: deg
  pitch: 0.0
  roll: 0.0
  x: 0.0 # unit: m
  y: 0.0
  z: -2.3

# camera config  
camera_pose_in_ego_frame:
  yaw: 90.0 # unit: deg
  pitch: 0.0
  roll: 90.0
  x: 0.0 # unit: m
  y: 0.0
  z: -2.0
camera_intrinsic_matrix:
  fx: 700.0
  fy: 700.0
  cx: 640.0
  cy: 360.0  
image_width: 1280
image_height: 720  

# noise
lidar_pcl_noise: 0.03 #unit: m
initial_rotation_noise: 2 #unit: deg
initial_translation_noise: 0.2 #unit: m

# others
delta_time_between_two_frame: 0.1 #unit: sec
generate_3d_data: true

